version: '3'
services:
  web:
    container_name: dragon-web
    image: 970863783/web:latest
    networks:
      - dragon-net
    ports:
      - 18888:80
    restart: always

  gateway:
    container_name: dragon-gateway
    image: 970863783/gateway:latest
    env_file:
      - ../env/application.env
    networks:
      - dragon-net
    ports:
      - 10082:8080
    restart: always

  auth-server:
    container_name: dragon-auth-server
    image: 970863783/auth-server:latest
    env_file:
      - ../env/application.env
    networks:
      - dragon-net
    restart: always

  resource-server:
    container_name: dragon-resource-server
    image: 970863783/resource-server:latest
    env_file:
      - ../env/application.env
    networks:
      - dragon-net
    restart: always

  code-generator:
    container_name: dragon-code-generator
    image: 970863783/code-generator:latest
    env_file:
      - ../env/application.env
    networks:
      - dragon-net
    restart: always

networks:
  dragon-net:
    external: true