version: '3'
services:
  redis:
    image: redis:6.2.4
    container_name: dragon-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ../data/redis:/data
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - dragon-net
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management
    container_name: dragon-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - dragon-net
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - ../env/rabbitmq.env

  mysql:
    image: mysql:5.7
    container_name: dragon-mysql
    restart: always
    networks:
      - dragon-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    env_file:
      - ../env/mysql.env

  minio:
    image: minio/minio
    container_name: dragon-minio
    command: server /data
    restart: always
    networks:
      - dragon-net
    ports:
      - 9000:9000
    volumes:
      - ../data/minio/data:/data
      - ../data/minio/config:/root/.minio
    env_file:
      - ../env/minio.env

networks:
  dragon-net:
    external: true